[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm install --prefix dashboard"
]

[phases.build]
cmds = [
  "npm run build --prefix dashboard"
]

[start]
cmd = "bash start.sh"
